### ISSUE TITLE
Djvu files not opened

### ISSUE THREAD

**Issue by larkang** [smathot/qnotero#22] opened 2015-10-01 09:53 UTC
I have some attachments in djvu format, which are not opened with qnotero, although they can be read by my document viewer (okular).

**Comment by smathot** [comment] 2015-10-02 07:59
Thanks for pointing this out! Once I find some time for a small update, I'll probably include this one as well.

**Comment by smathot** [comment] 2015-10-02 08:00
Closing as duplicate of #4.

**Closed by smathot** 2015-10-02 08:00 UTC
Labels: Minor
